(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let grade=Number(localStorage.getItem('review_active_grade'))||0;
let course=null,state=null,profile=STORE.loadProfile(),quiz=null,timerHandle=null;
const letters=['A','B','C','D'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const topicBy=id=>course.topics.find(t=>t.id===id), lessonBy=id=>course.lessons.find(l=>l.id===id);
const questionsForLesson=id=>course.questions.filter(q=>q.lessonId===id), questionsForTopic=id=>course.questions.filter(q=>q.topicId===id);
function selectGrade(g){grade=Number(g);course=COURSES[grade];if(!course)return;localStorage.setItem('review_active_grade',grade);state=STORE.load(grade);applyTheme();renderShell();hideCourseGate();showStudentGate(false);show('home');}
function showCourseGate(){const x=$('#courseGate');x.classList.add('show');x.setAttribute('aria-hidden','false');document.body.classList.add('gate-open');}
function hideCourseGate(){const x=$('#courseGate');x.classList.remove('show');x.setAttribute('aria-hidden','true');document.body.classList.remove('gate-open');}
function showStudentGate(force=false){if(!course)return;const missing=!profile.name.trim()||!profile.className.trim();const x=$('#studentGate');if(!force&&!missing){x.classList.remove('show');x.setAttribute('aria-hidden','true');document.body.classList.remove('gate-open');updateStudentBadge();return;}$('#gateName').value=profile.name||'';$('#gateClass').value=profile.className||'';$('#gateCode').value=profile.studentCode||'';$('#gateError').textContent='';x.classList.add('show');x.setAttribute('aria-hidden','false');document.body.classList.add('gate-open');}
function saveProfile(){const name=$('#gateName').value.trim(),className=$('#gateClass').value.trim(),studentCode=$('#gateCode').value.trim();if(!name||!className){$('#gateError').textContent='Vui lòng nhập đầy đủ Họ và tên và Lớp.';return;}profile={name,className,studentCode};STORE.saveProfile(profile);showStudentGate(false);}
function updateStudentBadge(){const b=$('#studentBadge');b.textContent=profile.name&&profile.className?`👤 ${profile.name} · ${profile.className}`:'👤 Chưa nhập thông tin';}
function save(){STORE.save(grade,state);renderStats();}
function applyTheme(){document.documentElement.dataset.theme=state?.theme==='dark'?'dark':'light';if($('#themeBtn'))$('#themeBtn').textContent=state?.theme==='dark'?'☀️':'🌙';}
function renderShell(){
 $('#courseBadge').textContent=grade;$('#brandTitle').textContent=`TIN HỌC ${grade}`;$('#brandSub').textContent='Ôn tập tương tác';
 $('#heroEyebrow').textContent=`TIN HỌC ${grade} · KẾT NỐI TRI THỨC VỚI CUỘC SỐNG`;
 $('#heroTitle').innerHTML=`ÔN TẬP TIN HỌC ${grade}<br><span class="gradient">HỌC CHẮC · LUYỆN ĐÚNG</span>`;
 $('#heroText').textContent=`${course.topics.length} chủ đề · ${course.lessons.length} bài học · ${course.questions.length} câu hỏi tĩnh. Học theo bài, luyện theo chủ đề, ôn câu sai và thi thử 45 phút.`;
 $('#courseNote').textContent=course.note||'';$('#footerCourse').textContent=`Website ôn tập Tin học ${grade}`;
 $('#topicHeading').textContent=`${course.topics.length} chủ đề · ${course.lessons.length} bài học`;
 $('#lessonHeading').textContent=`Tin học ${grade} · ${course.lessons.length} bài học`;
 renderCourseCards();renderStats();renderTopics();renderLessonsAll();renderPractice();renderFlashcards();renderGuide();updateStudentBadge();
}
function renderCourseCards(){const root=$('#homeCourseCards');root.innerHTML=[10,11].map(g=>{const c=COURSES[g];return `<button class="course-mini ${g===grade?'active':''}" data-switch="${g}"><span class="big">${g}</span><span><h3>${c.name}</h3><p>${c.topics.length} chủ đề · ${c.lessons.length} bài · ${c.questions.length} câu</p></span></button>`}).join('');root.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>selectGrade(b.dataset.switch));}
function renderStats(){if(!course||!state)return;let pct=Math.round(state.completedLessons.length/course.lessons.length*100);$('#statTopics').textContent=course.topics.length;$('#statLessons').textContent=course.lessons.length;$('#statQuestions').textContent=course.questions.length;$('#statProgress').textContent=pct+'%';$('#progressText').textContent=`${state.completedLessons.length}/${course.lessons.length} bài`;$('#progressBar').style.width=pct+'%';}
function show(name){$$('.view').forEach(v=>v.classList.remove('active'));const v=$(`#view-${name}`);if(v)v.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});$('#navLinks').classList.remove('open');}
function renderTopics(){const root=$('#topicGrid');root.innerHTML=course.topics.map(t=>{let qs=questionsForTopic(t.id).length;return `<article class="topic-card"><div class="topic-icon">${t.icon}</div><div><span class="eyebrow">CHỦ ĐỀ ${t.id}</span><h3>${esc(t.name)}</h3><p>${t.lessons.length} bài · ${qs} câu hỏi</p><button class="btn primary" data-topic="${t.id}">Mở chủ đề</button> <button class="btn ghost" data-topicquiz="${t.id}">Luyện 20 câu</button></div></article>`}).join('');root.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>openTopic(+b.dataset.topic));root.querySelectorAll('[data-topicquiz]').forEach(b=>b.onclick=()=>startQuiz(pickQuestions(questionsForTopic(+b.dataset.topicquiz),20),{mode:'topic',title:`Luyện Chủ đề ${b.dataset.topicquiz}`,timer:0}));}
function renderLessonsAll(){const root=$('#lessonGridAll');root.innerHTML=course.lessons.map(l=>lessonCard(l)).join('');bindLessonCards(root);}
function lessonCard(l){let qn=questionsForLesson(l.id).length,done=state.completedLessons.includes(l.id);return `<button class="lesson-card ${done?'done':''}" data-lesson="${l.id}"><span>BÀI ${l.id}</span><strong>${esc(l.title)}</strong><small>${qn} câu hỏi ${done?'· ✓ Đã hoàn thành':''}</small></button>`;}
function bindLessonCards(root){root.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(+b.dataset.lesson));}
function openTopic(id){let t=topicBy(id),ls=t.lessons.map(lessonBy).filter(Boolean);$('#topicDetail').innerHTML=`<button class="text-btn" id="backTopics">← Chủ đề</button><div class="lesson-hero"><span class="eyebrow">CHỦ ĐỀ ${t.id}</span><h2>${esc(t.name)}</h2><p>${ls.length} bài · ${questionsForTopic(id).length} câu hỏi</p><button class="btn primary" id="topicQuizBtn">Luyện 20 câu chủ đề</button></div><div class="lesson-grid">${ls.map(lessonCard).join('')}</div>`;$('#backTopics').onclick=()=>show('topics');$('#topicQuizBtn').onclick=()=>startQuiz(pickQuestions(questionsForTopic(id),20),{mode:'topic',title:`Chủ đề ${id} – ${t.name}`,timer:0});bindLessonCards($('#topicDetail'));show('topic');}
function levelCounts(qs){return course.levels.map(l=>[l,qs.filter(q=>q.level===l).length]);}
function openLesson(id){let l=lessonBy(id),qs=questionsForLesson(id),done=state.completedLessons.includes(id);let cards=l.summary.map((s,i)=>`<div class="remember"><b>${i+1}. Kiến thức trọng tâm</b><span>${esc(s)}</span></div>`).join('');$('#lessonDetail').innerHTML=`<button class="text-btn" id="backLessons">← Danh sách bài</button><div class="lesson-hero"><span class="eyebrow">BÀI ${l.id} · CHỦ ĐỀ ${l.topic}</span><h2>${esc(l.title)}</h2><p>${esc(topicBy(l.topic).name)}</p><div class="question-counts">${levelCounts(qs).map(x=>`<span>${x[0]}: ${x[1]}</span>`).join('')}</div><div class="lesson-quiz-actions"><button class="btn primary" id="lessonQuiz">Luyện 10 câu</button><button class="btn ghost" id="lessonAll">Luyện toàn bộ ${qs.length} câu</button><button class="btn ${done?'ghost':'primary'}" id="completeLesson">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button></div></div><div class="content-grid"><div class="panel"><h3>Kiến thức cần nhớ</h3><div style="display:grid;gap:10px">${cards}</div></div><div class="panel"><h3>Flashcard nhanh</h3><div class="flashcard" id="singleFlash"><div class="flash-inner"><div class="flash-front"><small>BÀI ${l.id}</small><strong>${esc(l.title)}</strong><span>Nhấp để lật</span></div><div class="flash-back"><small>GỢI NHỚ</small><strong>${esc(l.summary[0])}</strong></div></div></div></div></div>`;$('#backLessons').onclick=()=>show('lessons');$('#lessonQuiz').onclick=()=>startQuiz(pickQuestions(qs,10),{mode:'lesson',title:`Bài ${l.id} – ${l.title}`,lessonId:id,timer:0});$('#lessonAll').onclick=()=>startQuiz(shuffle(qs),{mode:'lesson-all',title:`Bài ${l.id} – Toàn bộ câu hỏi`,lessonId:id,timer:0});$('#completeLesson').onclick=()=>{state.completedLessons=state.completedLessons.includes(id)?state.completedLessons.filter(x=>x!==id):[...state.completedLessons,id];save();openLesson(id);renderLessonsAll();renderTopics();};$('#singleFlash').onclick=e=>e.currentTarget.classList.toggle('flipped');show('lesson');}
function renderFlashcards(){let cards=course.lessons.flatMap(l=>l.summary.map((s,i)=>({l,s,i})));let idx=0;const root=$('#flashContent');function paint(){let x=cards[idx];root.innerHTML=`<div class="section-head"><div><span class="eyebrow">FLASHCARD · ${idx+1}/${cards.length}</span><h2>Bài ${x.l.id}. ${esc(x.l.title)}</h2></div></div><div class="panel"><div class="flashcard" id="globalFlash"><div class="flash-inner"><div class="flash-front"><small>NHẤP ĐỂ LẬT</small><strong>${esc(x.l.title)}</strong></div><div class="flash-back"><small>GỢI NHỚ ${x.i+1}</small><strong>${esc(x.s)}</strong></div></div></div><div class="flash-controls"><button class="btn ghost" id="flashPrev">← Trước</button><button class="btn primary" id="flashNext">Sau →</button></div></div>`;$('#globalFlash').onclick=e=>e.currentTarget.classList.toggle('flipped');$('#flashPrev').onclick=()=>{idx=(idx-1+cards.length)%cards.length;paint()};$('#flashNext').onclick=()=>{idx=(idx+1)%cards.length;paint()};}paint();}
function renderPractice(){const root=$('#practiceContent');root.innerHTML=`<div class="section-head"><div><span class="eyebrow">LUYỆN TẬP</span><h2>Chọn cách luyện Tin học ${grade}</h2><p>Câu hỏi được lấy từ ngân hàng tĩnh đã tích hợp trong website.</p></div></div><div class="practice-grid"><article class="practice-card"><div class="review-icon">🎯</div><h3>Luyện ngẫu nhiên</h3><p>20 câu từ toàn bộ chương trình.</p><button class="btn primary" id="random20">Bắt đầu</button></article><article class="practice-card"><div class="review-icon">🧩</div><h3>Luyện câu sai</h3><p>Ôn lại các câu đã trả lời sai.</p><button class="btn primary" id="practiceWrong">Mở câu sai</button></article><article class="practice-card"><div class="review-icon">⏱</div><h3>Thi thử</h3><p>30 câu · 45 phút · chỉ xem đáp án sau khi nộp.</p><button class="btn primary" id="practiceExam">Thi thử ngay</button></article></div><div class="panel"><h3>Luyện theo chủ đề</h3><div class="level-actions">${course.topics.map(t=>`<button class="btn ghost" data-p-topic="${t.id}">Chủ đề ${t.id}</button>`).join('')}</div></div>`;$('#random20').onclick=()=>startQuiz(pickQuestions(course.questions,20),{mode:'practice',title:`Luyện ngẫu nhiên Tin ${grade}`,timer:0});$('#practiceWrong').onclick=()=>renderWrong();$('#practiceExam').onclick=()=>startExam();root.querySelectorAll('[data-p-topic]').forEach(b=>b.onclick=()=>startQuiz(pickQuestions(questionsForTopic(+b.dataset.pTopic),20),{mode:'topic',title:`Luyện Chủ đề ${b.dataset.pTopic}`,timer:0}));}
function pickQuestions(pool,n){return shuffle(pool).slice(0,Math.min(n,pool.length));}
function startExam(){startQuiz(pickQuestions(course.questions,course.examQuestions),{mode:'exam',title:`Thi thử Tin học ${grade} – 30 câu`,timer:course.examMinutes*60});}
function startQuiz(qs,opts){if(!profile.name||!profile.className){showStudentGate(true);return;}clearInterval(timerHandle);quiz={qs:[...qs],opts,index:0,answers:{},start:Date.now(),remaining:opts.timer||0,submitted:false};$('#quizTitle').textContent=opts.title;$('#quizStudent').textContent=`${profile.name} · ${profile.className} · Khối ${grade}`;renderQuestion();if(opts.timer){$('#quizTimer').textContent=`⏱ ${fmtTime(quiz.remaining)}`;timerHandle=setInterval(()=>{quiz.remaining--;$('#quizTimer').textContent=`⏱ ${fmtTime(quiz.remaining)}`;if(quiz.remaining<=0){clearInterval(timerHandle);finishQuiz();}},1000);}else $('#quizTimer').textContent='Không giới hạn';show('quiz');}
function fmtTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function renderQuestion(){let q=quiz.qs[quiz.index],sel=quiz.answers[q.id];$('#quizCounter').textContent=`Câu ${quiz.index+1}/${quiz.qs.length}`;$('#quizProgress').style.width=((quiz.index+1)/quiz.qs.length*100)+'%';let exam=quiz.opts.mode==='exam';$('#quizBody').innerHTML=`<div class="quiz-meta"><span>${esc(q.level)}</span><span>Bài ${q.lessonId}</span><span>Chủ đề ${q.topicId}</span></div><h2>${esc(q.question)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${sel===i?'selected':''}" data-option="${i}"><b>${letters[i]}</b><span>${esc(o)}</span></button>`).join('')}</div><div id="feedback"></div><div class="quiz-actions"><button class="btn ghost" id="prevQ" ${quiz.index===0?'disabled':''}>← Trước</button><div>${!exam&&sel!==undefined?'<button class="btn ghost" id="checkQ">Xem giải thích</button> ':''}${quiz.index===quiz.qs.length-1?'<button class="btn primary" id="finishQ">Nộp bài</button>':'<button class="btn primary" id="nextQ">Tiếp →</button>'}</div></div>`;$('#quizBody').querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{quiz.answers[q.id]=+b.dataset.option;renderQuestion();if(!exam)showFeedback(q);});if($('#prevQ'))$('#prevQ').onclick=()=>{quiz.index--;renderQuestion()};if($('#nextQ'))$('#nextQ').onclick=()=>{quiz.index++;renderQuestion()};if($('#finishQ'))$('#finishQ').onclick=finishQuiz;if($('#checkQ'))$('#checkQ').onclick=()=>showFeedback(q);if(!exam&&sel!==undefined)showFeedback(q);}
function showFeedback(q){let sel=quiz.answers[q.id];if(sel===undefined)return;let ok=sel===q.correctAnswer;let f=$('#feedback');f.innerHTML=`<div class="feedback ${ok?'ok':'bad'}"><b>${ok?'✓ Chính xác':'✗ Chưa đúng'}</b><p>Đáp án: <span class="answer-key">${letters[q.correctAnswer]}. ${esc(q.options[q.correctAnswer])}</span></p><p>${esc(q.explanation)}</p></div>`;$('#quizBody').querySelectorAll('[data-option]').forEach((b,i)=>{b.classList.toggle('choice-correct',i===q.correctAnswer);b.classList.toggle('choice-wrong',i===sel&&!ok);});}
function finishQuiz(){if(quiz.submitted)return;quiz.submitted=true;clearInterval(timerHandle);let correct=0,answered=0,byLevel={},byTopic={};quiz.qs.forEach(q=>{let a=quiz.answers[q.id],ok=a===q.correctAnswer;if(a!==undefined)answered++;if(ok)correct++;if(!byLevel[q.level])byLevel[q.level]={right:0,total:0};byLevel[q.level].total++;if(ok)byLevel[q.level].right++;if(!byTopic[q.topicId])byTopic[q.topicId]={right:0,total:0};byTopic[q.topicId].total++;if(ok)byTopic[q.topicId].right++;if(a!==undefined){state.attempted++;if(ok){state.correct++;state.wrongIds=state.wrongIds.filter(id=>id!==q.id);}else if(!state.wrongIds.includes(q.id))state.wrongIds.push(q.id);}});let total=quiz.qs.length,pct=Math.round(correct/total*100),point=(correct/total*10).toFixed(1);if(quiz.opts.lessonId&&!state.completedLessons.includes(quiz.opts.lessonId))state.completedLessons.push(quiz.opts.lessonId);let hist={date:new Date().toISOString(),title:quiz.opts.title,point:Number(point),score:correct,total};if(quiz.opts.mode==='exam')state.examHistory.unshift(hist);save();renderLessonsAll();renderTopics();let review=quiz.qs.map((q,i)=>{let a=quiz.answers[q.id],ok=a===q.correctAnswer;return `<article class="review-item ${ok?'ok':'bad'}"><b>Câu ${i+1}: ${esc(q.question)}</b><p>Em chọn: ${a===undefined?'Chưa trả lời':letters[a]+'. '+esc(q.options[a])}</p><p>Đáp án: <strong>${letters[q.correctAnswer]}. ${esc(q.options[q.correctAnswer])}</strong></p><small>${esc(q.explanation)}</small></article>`}).join('');$('#resultContent').innerHTML=`<div class="result-hero"><div class="score-ring" style="--p:${pct}"><div><strong>${point}</strong><span>/10</span></div></div><div><span class="eyebrow">KẾT QUẢ · TIN HỌC ${grade}</span><h2>${correct}/${total} câu đúng · ${pct}%</h2><p>${esc(profile.name)} · ${esc(profile.className)} · đã trả lời ${answered}/${total} câu.</p><div id="resultSyncStatus" class="sync-status">Chuẩn bị gửi kết quả...</div><div class="result-actions"><button class="btn primary" id="retryBtn">Làm lại</button><button class="btn ghost" id="homeAfter">Trang chủ</button></div></div></div><div class="metrics">${course.levels.map(l=>{let x=byLevel[l]||{right:0,total:0};return `<div class="metric"><b>${x.right}/${x.total}</b><span>${l}</span></div>`}).join('')}</div><div class="panel"><h3>Đáp án và giải thích</h3>${review}</div>`;$('#retryBtn').onclick=()=>startQuiz(pickQuestions(quiz.qs,quiz.qs.length),quiz.opts);$('#homeAfter').onclick=()=>show('home');show('results');sendResult(resultPayload(correct,total,point,pct,answered,byTopic,byLevel));}
function appConfig(){return window.APP_CONFIG||{}}function endpoint(){return String(appConfig().RESULTS_ENDPOINT||'').trim()}function configured(){return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(endpoint())}function deviceId(){let x=localStorage.getItem('tin_review_device_id');if(!x){x=(crypto.randomUUID?crypto.randomUUID():`dev-${Date.now()}-${Math.random()}`);localStorage.setItem('tin_review_device_id',x)}return x}
function resultPayload(correct,total,point,pct,answered,byTopic,byLevel){let lv=n=>byLevel[n]||{right:0,total:0};return {studentName:profile.name,className:profile.className,studentCode:profile.studentCode,grade:String(grade),sessionType:quiz.opts.mode,quizTitle:quiz.opts.title,score10:point,correct,total,percent:pct,answered,durationSeconds:Math.max(0,Math.round((Date.now()-quiz.start)/1000)),nbCorrect:lv('Nhận biết').right,nbTotal:lv('Nhận biết').total,thCorrect:lv('Thông hiểu').right,thTotal:lv('Thông hiểu').total,vdCorrect:lv('Vận dụng').right,vdTotal:lv('Vận dụng').total,vdcCorrect:lv('Vận dụng cao').right,vdcTotal:lv('Vận dụng cao').total,topicSummary:JSON.stringify(byTopic),attemptId:(crypto.randomUUID?crypto.randomUUID():`att-${Date.now()}`),deviceId:deviceId(),submittedAt:new Date().toISOString(),pageUrl:location.href,userAgent:navigator.userAgent};}
function sendResult(payload){let status=$('#resultSyncStatus');if(!configured()){if(status)status.innerHTML='⚠️ <strong>Chưa kết nối Google Sheet.</strong> Kết quả vẫn lưu trên thiết bị.';return;}let sink=$('#resultSink'),form=document.createElement('form');form.method='POST';form.action=endpoint();form.target='resultSink';form.style.display='none';let input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify(payload);form.appendChild(input);document.body.appendChild(form);form.submit();form.remove();if(status)status.innerHTML='📤 Đã gửi yêu cầu ghi kết quả về Google Sheets.';}
function renderWrong(){let qs=course.questions.filter(q=>state.wrongIds.includes(q.id));$('#wrongContent').innerHTML=`<div class="section-head"><div><span class="eyebrow">SỔ CÂU SAI</span><h2>${qs.length} câu cần ôn lại</h2></div>${qs.length?'<button class="btn primary" id="wrongQuiz">Luyện các câu sai</button>':''}</div>${qs.length?`<div class="wrong-list">${qs.map(q=>`<article><span>${esc(q.lesson)} · ${q.level}</span><b>${esc(q.question)}</b><small>Đáp án đúng: ${letters[q.correctAnswer]}. ${esc(q.options[q.correctAnswer])}</small></article>`).join('')}</div>`:'<div class="empty"><div>🎉</div><h3>Chưa có câu sai cần ôn</h3></div>'}`;if($('#wrongQuiz'))$('#wrongQuiz').onclick=()=>startQuiz(shuffle(qs),{mode:'wrong',title:'Ôn câu sai',timer:0});show('wrong');}
function renderProgress(){let acc=state.attempted?Math.round(state.correct/state.attempted*100):0,best=state.examHistory.length?Math.max(...state.examHistory.map(x=>x.point)):0;$('#progressContent').innerHTML=`<div class="section-head"><div><span class="eyebrow">TIẾN ĐỘ · TIN ${grade}</span><h2>${esc(profile.name||'Học sinh')}</h2><p>${esc(profile.className||'Chưa nhập lớp')}</p></div></div><div class="metrics"><div class="metric"><b>${state.completedLessons.length}/${course.lessons.length}</b><span>Bài hoàn thành</span></div><div class="metric"><b>${state.attempted}</b><span>Câu đã làm</span></div><div class="metric"><b>${acc}%</b><span>Độ chính xác</span></div><div class="metric"><b>${best.toFixed(1)}</b><span>Điểm thi thử cao nhất</span></div></div><div class="panel"><h3>Bài đã hoàn thành</h3><div class="lesson-grid">${course.lessons.map(lessonCard).join('')}</div></div><div class="danger-zone"><b>Đặt lại tiến độ Tin học ${grade}</b><p class="muted">Không xoá thông tin họ tên, chỉ xoá tiến độ/câu sai/lịch sử của khối hiện tại.</p><button class="btn danger" id="resetProgress">Đặt lại tiến độ</button></div>`;bindLessonCards($('#progressContent'));$('#resetProgress').onclick=()=>{if(confirm('Đặt lại toàn bộ tiến độ khối '+grade+'?')){state=STORE.reset(grade);applyTheme();renderShell();renderProgress();}};show('progress');}
function renderGuide(){let root=$('#guideContent');root.innerHTML=`<div class="section-head"><div><span class="eyebrow">HƯỚNG DẪN</span><h2>Sử dụng website Tin học 10 & 11</h2></div></div><div class="guide-grid"><div class="panel"><h3>Dành cho học sinh</h3><ol class="step-list"><li>Bấm số khối ở góc trên hoặc “Đổi khối” để chọn Tin 10/Tin 11.</li><li>Nhập Họ tên và Lớp. Thông tin được dùng khi gửi kết quả.</li><li>Học theo Chủ đề/Bài; làm luyện tập; xem giải thích ngay.</li><li>Thi thử: 30 câu, 45 phút; xem đáp án sau khi nộp.</li><li>Câu trả lời sai được lưu riêng theo từng khối để ôn lại.</li></ol></div><div class="panel"><h3>Dành cho giáo viên</h3><p>Google Apps Script nhận thêm trường <b>Khối</b> và số câu <b>Vận dụng cao</b>. Hãy dùng tệp <code>GOOGLE_APPS_SCRIPT_Code.gs.txt</code> trong gói này rồi triển khai lại Web App.</p><p class="notice">URL Web App hiện tại đã được giữ trong <code>config.js</code>. Nếu triển khai lại cùng deployment, website không cần đổi URL.</p><p>${esc(COURSE10.note)}</p></div></div>`;}
function search(q){q=q.trim().toLowerCase();let root=$('#searchResults');if(!q){root.innerHTML='';return;}let ls=course.lessons.filter(l=>(`${l.id} ${l.title} ${l.summary.join(' ')}`).toLowerCase().includes(q)).slice(0,8);root.innerHTML=ls.length?ls.map(l=>`<button data-search-lesson="${l.id}"><b>Bài ${l.id}. ${esc(l.title)}</b><small>${esc(topicBy(l.topic).name)}</small></button>`).join(''):'<div class="no-result">Không tìm thấy bài phù hợp.</div>';root.querySelectorAll('[data-search-lesson]').forEach(b=>b.onclick=()=>{root.innerHTML='';$('#searchInput').value='';openLesson(+b.dataset.searchLesson)});}
function bind(){
 $$('#navLinks [data-nav]').forEach(a=>a.onclick=e=>{e.preventDefault();let n=a.dataset.nav;if(n==='wrong')renderWrong();else if(n==='progress')renderProgress();else show(n)});
 $('#menuBtn').onclick=()=>$('#navLinks').classList.toggle('open');$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};$('#studentBadge').onclick=()=>showStudentGate(true);$('#gateSaveBtn').onclick=saveProfile;$('#courseBadge').onclick=showCourseGate;$('#switchCourseBtn').onclick=showCourseGate;$$('.course-choice').forEach(b=>b.onclick=()=>selectGrade(b.dataset.grade));$('#startBtn').onclick=()=>show('topics');$('#examBtn').onclick=startExam;$('#examBtn2').onclick=startExam;$('#wrongBtn').onclick=renderWrong;$('#searchInput').addEventListener('input',e=>search(e.target.value));
}
bind();if(grade&&COURSES[grade])selectGrade(grade);else showCourseGate();
})();
